### ISSUE TITLE
Multiple new lines are always rendered as one

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#101]
When a message content contains chained newlines (e.g. two newlines to form a new paragraph), they are always rendered as one new line. This bug occurs for both human messages and bot messages. You can see the actual newlines by editing a message.

Rendered:

![1680005815](https://user-images.githubusercontent.com/128472336/228234492-8c55646f-cc96-48b9-80f4-6859b895dc5e.png)

Editing:

![1680005821](https://user-images.githubusercontent.com/128472336/228234514-bf820c83-1281-453f-b7af-3652bd34afed.png)

Can attempt a PR with your OK.

**Comment by gtaltatra** [comment]
I wasn't sure if it was a bug, but yeah, it's a little annoying.

**Comment by sceuick** [comment]
I've looked into this previously. I _think_ multiple line breaks are deliberately removed or there is a limitation in the markdown library. I'll look into it again. If it is as simple as being too aggressive removing line breaks, I can probably replace "two or more line breaks" with just two line breaks instead of one.
