### ISSUE TITLE
UX: Puzzling UX for Single and Multi chat input

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#126]
From my testing, this is how I understand Single and Multi to function:

- Single: Enter sends the message. No way to create newlines.
- Multi: Enter sends the message. You can create a newline with Shift-Enter.

In other words, all Single mode does is disable the Shift-Enter shortcut. What even is the point of Single mode, and why is it the default? I believe the UX should be reworked, or the setting removed. For example, current Multi mode could be the default, and an alternative mode (let's name it Phone-Friendly) could be:

- Enter creates a new line
- "Send message" icon is restored for easy sending on phone
- Shift-Enter and Ctrl-Enter send the message

If the setting is removed, another way to communicate to users that Shift-Enter must be designed.

### Bonus related issues

- Visual bug: Pressing enter while the cursor is in the middle of text briefly creates a newline in the input, must fix.
- Ctrl-Enter currently does nothing. An anonymous user has requested that it sends a message.

**Comment by acidbubbles** [comment]
Fixed in #146

- ctrl+enter now sends
- No more empty line added on send using enter (the "visual bug)
- No more multi v.s. single (they did the same thing, really...)
- shift+enter always works (multi by default)

I guess the shift+enter _could_ be communicated, but it's pretty ubiquitous, and if you don't know, honestly, I'd say it's not really a problem. I'll leave to your judgment @malfoyslastname to close the issue or not (if my PR is merged ;) )

**Comment by malfoyslastname** [comment]
fine to close after merge

**Comment by sceuick** [comment]
The single line input has been removed.
