### ISSUE TITLE
Feat: Cut incomplete sentences

### ISSUE THREAD

**Issue by acidbubbles** [agnaistic/agnai#162]
In some cases the AI will write an incomplete sentence at the end of a long text. It would be nice to cut it off completely. Something like "if there's at least one dot, cut off everything after the last dot, asterisk, closing parenthesis or quote".

I'd make this optional.

Example:

```
*I laugh* that was a funny joke! I think I heard one like this before. I was
```

**Comment by sceuick** [comment]
This can probably be a UI setting, but then the incomplete sentence would still be in the prompt.
Perhaps it's best suited as a generation setting?

**Comment by rondlite** [comment]
Just a sidenote, I think this mainly happens when the AI runs out of tokens, since it even happens when you have Kobold set to do cut incomplete lines. So maybe a good start is to check if all tokens are used in the reply and if so, do a trim on last dot. 
I am assuming that when the AI has the chance to finish a line, it will. Running out of tokens takes away that chance..

**Comment by sceuick** [comment]
I often use the 'generate more' when this happens to me. Trimming to the last dot will break responses that end with emotes or end with other punctuation. E.g.:
`Bot: Hello world!`
`Bot: Hello world. *waves*`

**Comment by rondlite** [comment]
same here, I think the only solution i can think off is finishing a sentence with ... if there is a letter as last character and only have it visual in the output.
I think all you need is proper explain on when and how to use Generate more, and not bother further with it, at least not as a default setting.

**Comment by sceuick** [comment]
This is now a UI option.
