### ISSUE TITLE
Feat: Streaming support (show characters as they are generated, OpenAI, Claude and others that support it)

### ISSUE THREAD

**Issue by acidbubbles** [agnaistic/agnai#271]
I saw Claude supports streaming: using SSE https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

@malfoyslastname did you consider it? I'm just curious if I should maybe look at it or if you had a reason not to implement it using streams.

**Comment by malfoyslastname** [comment]
@acidbubbles can you explain what the benefit is considering agnai only shows the completion after it's been fully received anyway?

**Comment by sceuick** [comment]
Agnai has support for streaming in adapters (that's why they're generator functions), but it's not used anywhere anymore.
The original Kobold implementation would use a smaller `max tokens` size and generate multiple times, but I ripped that out a very long time ago.

ETA: This isn't a particularly high priority at all, just that it is supported. The `partial` property in the message store is intended for token streaming.

**Comment by acidbubbles** [comment]
@malfoyslastname I was _sure_ I saw streaming support but it seems I mixed up other chatbots, sorry about that! I'll just rename this to support streaming "in general", it'd be nice but indeed probably not that important.

**Comment by malfoyslastname** [comment]
supporting streaming in general would be nice indeed. (I don't personally care much about this feature, I don't think I'll be the one working on it)

**Comment by gtaltatra** [comment]
>I don't personally care much about this feature,

I'm honestly interested why though? Seems like one of the most basic features to me.

**Comment by khanonnie** [comment]
If nobody else plans on tackling this I could probably do it, I had a half-working (okay, more like quarter-working) implementation in a quick throwaway adapter I built a while back.  Never finished it because I don't personally care about having token streaming (used to online RP with humans, so it never bothered me), so I didn't feel like putting in the UI work for something I was going to throw away anyway.  But I could certainly resurrect it for integration into the mainline OAI/Claude adapters.

I would need some feedback on where the opt-in for this feature should live as it would be adapter-specific. Is it a generation setting or is this page the right place?
![image](https://user-images.githubusercontent.com/92774204/235512072-ad3162d3-b157-4e6a-8577-f9584514fd9e.png)

**Comment by malfoyslastname** [comment]
as discussed privately, this setting should be part of preset settings, off by default. preset settings will soon be adapter specific.
presuming @nai-degen is continuing work on this.

**Comment by khanonnie** [comment]
OAI implementation for this ready for review in #295. Don't have a functional Anthropic key to implement Claude though it should be relatively straightforward by following the OAI adapter's lead.
