### ISSUE TITLE
[FEAT REQ] Assign model/adapter to a character

### ISSUE THREAD

**Issue by rondlite** [agnaistic/agnai#290]
I would be nice if a character could have a set model/adapter that would fit  with the character, 
with this feature, if a character is nsfw then you could assign a pygmalion model and when you create a bot with more knowledge you can assign it to an openai model.

Oppose to having to set this on a per chat basis, it feels more like a character based setting.

**Comment by sceuick** [comment]
This probably won't happen. I'm nearing the end of a big PR at the moment to simplify presets and adapters due to being incredibly confusing for newcomers and a lot existing users.

- "Service" presets are being removed
- "Default Service" is being removed
- "Chat adapter" is being removed
- "Adapter/Service" is being moved to the preset. A preset _must_ have a service.
- You will be able to select a preset when creating a chat.
- The user can optionally configure a "default preset" in their settings (this will be selected by default in the create chat -> preset dropdown.

In the future I can see preset/generation settings being attached to character cards as being part of a broadly accepted standard for services like Agnai.
