### ISSUE TITLE
OpenAI quota error

### ISSUE THREAD

**Issue by nuruori** [agnaistic/agnai#351]
while i was using OpenAI on the site, i got an error message saying that i exceeded my quota, and i indeed did. wanting to keep on using it, i made a new account on OpenAI with a new API key. i input the new key on the settings but i kept getting the same error message. so i thought if i made a new account on the site and made an entirely different bot that this could be fixed, but no. also when i checked the usage from the site just to be sure the new key was set, it showed me 0$, meaning it was really set. i get the same message whatever i try, and i am out of ideas. is there any way this could be fixed, or do i have to use another AI from now on? this is the error message below.

![Screenshot_20230521_132532](https://github.com/luminai-companion/agn-ai/assets/134202355/326e3294-0df3-43f0-940f-94b003f82f01)

**Comment by Rafario448** [comment]
You can only get openAI free 5$ credits per phone number upon login. Creating a new account with a previously used phone number will not work.
Tbh. gpt 3.5 turbo is extremely cheap, I say this being living in a underveloped country with a currency 5x undervalued from dolar, it is worth to pay for their API, as bonus, you can grace yourself sometimes with some gpt4 answers occasionally. (just ocasionally cuz gpt4 is extremely expensive)

As free options go that don't envolve returning to the CAI hell you can:
Use SillyTavern (runs loccally on your computer/not easy to run on a phone) and use Poe to keep using gpt3.5 for absolutely free. I don't know why Agnaistic doesn't have a way that sends prompts to online services like Silly does with Poe. (imagine if aganaistic was able to send the generated propts to some site that gives you free access to gpt4! would be funny).

As a worst option, you can use PygmalionAI with Horde or self hosting it with Kobold. I don't recommend this option because, Pgymalion and every other community owned AI received much less training, specially with lore related stuff. Using community owned AIs is the best future, but right now they are far from being able to truly compete.
If you decide to use pygmalion, remember to rewrite the your character descriptions using W++ formatting.

I personally don't like using Pygmalion and I preffer to go to the trouble of even manually copying the generated prompt from Agnaistic to chatGPT website than using Pygmalion in its current state. Just gpt 3.5 alone is well aware of the lore of pretty much any fictional universe you want, much more than CAI.

**Comment by sceuick** [comment]
Hi there, this is definitely not something Agnai can do anything about. This is a billing issue with OpenAI.
