### ISSUE TITLE
Add new and popular default presets

### ISSUE THREAD

**Issue by sceuick** [agnaistic/agnai#75]
There are many presets out in the wild that would be great additions.
The `default-presets.ts` could use with some more options.

**Comment by acidbubbles** [comment]
Would be nice if the presets had some description of what they do, especially if there are more. Or even better, in that screen see the entirety of the preset content.

**Comment by acidbubbles** [comment]
I've been wondering if I should help with that issue for a while... I thought I would share why I didn't. Related to #113 and #128, which involve a more general refactoring of presets.

I think it would be nice to have multiple gaslights, not necessarily as part of the preset. For example, it makes sense to ask to avoid repetition for Pygmalion, but it doesn't make much sense to do that for GPT-4 or Claude. So, I would suggest adding a separate library of "Gaslights", separately from the "Presets" themselves. That would avoid having tons of variations of settings AND system prompts.

For everything BUT the Gaslights, it's very Horde/Tavern/Pygmalion specific to have so many presets. For other backends like OpenAI and Claude, you _could_ have two (more creative, less creative) but that's pretty much it. The real variation is with gaslights, but again too many built-in prompts? I'm not sure. If you want to fiddle with cool trendy gaslights, copy them from some Discord. Otherwise, provide solid, general purpose prompts in Agnai. Which may not be aligned with the intent of this issue.

On another note; changing presets will break users (see linked issue) since the preset ID is fixed. So I'd use the opportunity to change how it works completely first, and then add more variation. But that's just an opinion :)
