### ISSUE TITLE
Refreshing Page to Get Generate More

### ISSUE THREAD

**Issue by sjess94** [agnaistic/agnai#793]
I'm having issues with a bug for the generate more feature.

To get the replies from the bot, I have to refresh the page. This doesn't happen when I reroll for a completely different response, only when I use the generate more feature.

**To Reproduce**
1. Go to an active chat.
2. Click on 'generate more'.
3. The reply will act like it's trying to load but never does. Refresh and the new response should be there.
4. There is no error code associated with this.

Smartphone:
 - Device: iPhone 15 Pro
 - OS: [e.g. iOS17.2.1
 - Browser: Safari

**Comment by Endovior** [comment]
I'm noticing something similar. Since yesterday, when I click Generate More, I do actually get the reply, but the bot stops responding further; it won't let me enter a reply of my own, won't respond to the buttons that'd normally regenerate the additional text or the whole reply, and if I attempt to edit the AI response, it won't show the newly added text. The only command I can send that the bot will actually accept is to delete the new message... unless I refresh the page. After refreshing, I'll keep the full and lengthened reply, and the bot will continue work normally until I click Generate More again.

This is particularly odd, since it was working fine at the beginning of this week.

For reference, I'm getting this on a Windows 10 desktop, in Firefox 121.0

I normally use NovelAI's Kayra for generation, but a quick test shows that I get the exact same results with Agnaistic's generator, so I assume it's not an AI-specific issue.

**Comment by sceuick** [comment]
Should be fixed now.
