### ISSUE TITLE
BUG Imported chat messages are inserted backwards

### ISSUE THREAD

**Issue by gtaltatra** [agnaistic/agnai#97]
2. Import chat
3. Test using oai or cbt 
4. Pic
![pic](https://user-images.githubusercontent.com/51547727/228085348-428f319c-16be-47d0-bc75-ad27b1f705f9.png)

**Comment by khanonnie** [comment]
I think this happened when @sceuick merged their Agnaistic implementation with my TavernAI one.  Looks like we lost the `timestamp` property on imported log lines, which I had assumed was necessary since the database sorts chat messages chronologically.  Without the timestamp, all imported messages get the same `createdAt` time (visible in the screenshot) and presumably the tiebreaker becomes (I guess?) reverse database insert order.

Might be possible to quickly fix this by adding `.reverse()` to the Tavern import parser, but re-adding `timestamp` might be preferable since database insert order is a bit of an opaque way for them to sort (if that is indeed what's happening).

**Comment by sceuick** [comment]
I'll get this all fixed up.

**Comment by khanonnie** [comment]
Actually they're sorting in the correct order in the chat UI but not when building the prompt, huh... 🤔

**Comment by sceuick** [comment]
Might be due to the timestamps all being the same. Need to constantly increment it most likely.

**Comment by sceuick** [comment]
Pushed some fixes for this. Let me know how they go.

**Comment by khanonnie** [comment]
> Pushed some fixes for this. Let me know how they go.

Works for logged-in users 👍 
needs the same fix for localstorage mode

**Comment by khanonnie** [comment]
Opened https://github.com/luminai-companion/agn-ai/pull/98 for the above
